Repository Daverhan/door-hinge-web-app, pull requests merged in 2024-04, with the labels that each got.

#42 feat: implement chat functionality
  backend/app.py
  backend/app/__init__.py
  backend/app/extensions.py
  backend/app/models/user.py
  backend/app/rbac_utilities.py
  backend/app/routes/chats.py
  backend/app/routes/users.py
  backend/migrations/versions/624ee34cda4e_.py
  backend/migrations/versions/66ca01da9890_.py
  backend/migrations/versions/673f8a238dc5_.py
  backend/requirements.txt
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Login.tsx
  frontend/src/components/Messages.tsx
  frontend/src/components/Signup.tsx
  frontend/src/interfaces.ts
Labels: enhancement

#43 fix: add types for TS files and remove debug statements
  backend/app/routes/chats.py
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Messages.tsx
  frontend/src/interfaces.ts
Labels: fix

#44 fix: adjust messages UI
  frontend/src/components/Messages.tsx
Labels: fix

#45 Update README.md
  README.md
Labels: good first issue

#41 Stephanie
  backend/.gitignore
  backend/app/models/user.py
  backend/app/rbac_utilities.py
  backend/app/routes/users.py
  backend/migrations/versions/f750d3bacb03_.py
  frontend/src/components/Favorites.tsx
  frontend/src/components/Moderator.tsx
Labels: enhancement
